name: Open Task

on:
  workflow_dispatch:
    inputs:
      task_id:
        description: "The task id for the corresponding task in Click Up"
        required: true
        
jobs:
  get_task_details:
    runs-on: ubuntu-latest
    outputs:
      branchname: ${{ steps.task_data_step.outputs.branchname }}
    steps:        
      - name: Get Task ClickUp
        env:
          TASK_ID: ${{ github.event.inputs.task_id }}
          API_TOKEN: ${{ secrets.CLICKUP_API_KEY }}
        id: task_data_step
        run: |
          echo "$TASK_ID"
          response=$(curl --location "https://api.clickup.com/api/v2/task/${TASK_ID}" \
          --header "Authorization: ${API_TOKEN}")
          taskname=$(echo "$response" | jq -r '.name')
          branchname=$(echo "$taskname" | sed -e 's/\(\w\)/\L\1/g' -e 's/[[:punct:][:space:]]/_/g' | cut -c 1-30)
          echo "$branchname"
          echo "branchname=$branchname" >> "$GITHUB_OUTPUT"

  open_task:
    needs: get_task_details
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repository
          uses: actions/checkout@v2

        - name: Create a new branch
          env:
            TASK_ID: ${{ github.event.inputs.task_id }}
            BRANCH_NAME: ${{ needs.get_task_details.outputs.branchname }}
          run: |
            echo "creating branch $BRANCH_NAME"
            git checkout -b "$BRANCH_NAME"
            git push origin "$BRANCH_NAME"
          
        - name: Update Task Status in ClickUp
          env:
            TASK_ID: ${{ github.event.inputs.task_id }}
            API_TOKEN: ${{ secrets.CLICKUP_API_KEY }}
          run: |
            curl --location --request PUT "https://api.clickup.com/api/v2/task/${TASK_ID}" \
            --header "Content-Type: application/json" \
            --header "Authorization: ${API_TOKEN}" \
            --data '{
                "status": "in progress"
            }'
            
        - name: Update Task GitHub Link in ClickUp
          env:
            TASK_ID: ${{ github.event.inputs.task_id }}
            BRANCH_NAME: ${{ needs.get_task_details.outputs.branchname }}
            API_TOKEN: ${{ secrets.CLICKUP_API_KEY }}
            REPO_URL: "https://github.com/Aniki219/DreamCats/tree"
          run: |
            curl --location "https://api.clickup.com/api/v2/task/${TASK_ID}/field/09619d65-23ce-4c38-ab24-c11f8bdcee71" \
            --header "Content-Type: application/json" \
            --header "Authorization: ${API_TOKEN}" \
            --data "{
                \"value\": \"${REPO_URL}/${BRANCH_NAME}\"
            }"
